//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroveStreat_BiblioEntities : DbContext
    {
        public GroveStreat_BiblioEntities()
            : base("name=GroveStreat_BiblioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookCategory> BookCategory { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Extradition> Extradition { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<IN_ReadingRoom> IN_ReadingRoom { get; set; }
        public virtual DbSet<Proizved> Proizved { get; set; }
        public virtual DbSet<ReadingRooms> ReadingRooms { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
